<a href="https://colab.research.google.com/github/Steve-YJ/Data-Science-scratch/blob/master/A_note_on_python_numpy_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python-Numpy vectors

In [4]:
import numpy as np

a = np.random.randn(5)

In [5]:
print(a)

[-0.28805695  0.06451027  1.14206386 -0.73870495  0.85652713]


In [7]:
print(a.shape)  # row vector

(5,)


In [8]:
print(a.T)

[-0.28805695  0.06451027  1.14206386 -0.73870495  0.85652713]


In [9]:
print(np.dot(a, a.T))

2.6707719779140584


a dot a.T get back a number... Why?! -20.11.02.Mon.pm6:40-

In [11]:
a = np.random.randn(5, 1)
print(a)

[[-1.38295489]
 [ 1.54524965]
 [ 0.68794602]
 [ 1.03365885]
 [-0.13903463]]


In [12]:
print(a.T)

[[-1.38295489  1.54524965  0.68794602  1.03365885 -0.13903463]]


1 by 5 Matrix instead

In [13]:
# So...

np.dot(a, a.T)

array([[ 1.91256423, -2.13701056, -0.95139832, -1.42950357,  0.19227862],
       [-2.13701056,  2.38779647,  1.06304835,  1.59726098, -0.21484321],
       [-0.95139832,  1.06304835,  0.47326973,  0.7111015 , -0.09564832],
       [-1.42950357,  1.59726098,  0.7111015 ,  1.06845063, -0.14371437],
       [ 0.19227862, -0.21484321, -0.09564832, -0.14371437,  0.01933063]])

In [14]:
assert(a.shape == (5, 1))