<a href="https://colab.research.google.com/github/Steve-YJ/Data-Science-scratch/blob/master/Week2_Broad_Casting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Broadcasting example

In [33]:
import numpy as np

eg = np.array([[56, 0, 4.4, 68],
               [1.2, 104, 52, 8],
               [1.8, 135, 99, 0.9]], dtype=np.float64)
eg

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [34]:
eg.sum(axis=0)

array([ 59. , 239. , 155.4,  76.9])

In [38]:
result = eg / eg.sum(axis=0)
result*100

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

## Andrew's Code

In [41]:
A = np.array([[56, 0, 4.4, 68],
             [1.2, 104, 52, 8],
             [1.8, 135, 99, 0.9]], dtype=np.float64)
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [42]:
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [47]:
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [49]:
percentage = 100*A/cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


Example

In [50]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([100, 200, 300])

print("A+B= ")
print(A+B)

A+B= 
[[101 202 303]
 [104 205 306]]
